function [ vehicleStruct ] = genTraffic( vehicleStruct,genData )
% GENTRAFFIC For each timeslot define the amount of data being generated by
% a vehicle. If the vehicle is an "Emergency Vehicle" type, the generated
% data are always the maximum value.
%
% Input:
%   vehicleStruct  :   This structure contains all the information about the vehicles
%                      such as the real position, the GPS position, the beacons, etc.
%   genData        :   Array with the values of the generated data.
%
% Output:
%   vehicleStruct  :   The vehicle structure is updated with the beacon
%                      information received from each vehicle               
%
% Copyright (c) 2016-2017, Ioannis Mavromatis

    for nodeIndex = 1:vehicleStruct.numNodes
        if vehicleStruct.vehNode(nodeIndex).V_TYPE ~= 1
            index = randi(4,1,length(vehicleStruct.vehNode(nodeIndex).V_TIME));
            tmpArray = (genData(index)*vehicleStruct.simStep)';
            tmpArray = tmpArray*1000000;
            vehicleStruct.vehNode(nodeIndex).GENDATA = tmpArray;
        else
            index = length(genData)*ones(length(vehicleStruct.vehNode(nodeIndex).V_TIME),1);
            tmpArray = (genData(index)*vehicleStruct.simStep)';
            tmpArray = tmpArray*1000000;
            vehicleStruct.vehNode(nodeIndex).GENDATA = tmpArray;
        end
    end
end

